import type {
  ScrapedPayload,
  SchemaGap,
  BenchmarkGap,
  EntityGap,
  RemediationBrief,
  JiraTicket
} from "./types";

export class BriefGenerator {
  static generateMarketerBrief(
    query: string,
    brandPayload: ScrapedPayload,
    competitorPayload: ScrapedPayload,
    schemaGaps: SchemaGap[],
    benchmarkGaps: BenchmarkGap[],
    entityGaps: EntityGap[]
  ): RemediationBrief {
    const title = `AI Search Content Remediation Brief: ${brandPayload.domain} vs ${competitorPayload.domain}`;
    const executiveSummary = `Diagnostic AI search visibility analysis reveals that ${competitorPayload.domain} wins citations for the prompt query "${query}" due to ${schemaGaps.length} missing Schema.org JSON-LD microdata definitions, ${benchmarkGaps.length} unstated numerical benchmarks/proof points, and ${entityGaps.length} omitted high-priority topic entities.`;

    let md = `# 🎯 AI Search Content Remediation Brief (Agency Client Deliverable)\n\n`;
    md += `* **Monitored Query:** \`${query}\`\n`;
    md += `* **Client / Brand Domain:** [${brandPayload.domain}](${brandPayload.url})\n`;
    md += `* **Winning Competitor Citation:** [${competitorPayload.domain}](${competitorPayload.url})\n`;
    md += `* **Generated By:** Peec AI Autonomous GEO Synthesizer\n\n`;
    md += `---\n\n## 📌 Executive Summary\n\n${executiveSummary}\n\n`;

    md += `## 1. 🔴 Missing Schema.org JSON-LD Markup\n\n`;
    md += `Search engines (ChatGPT Search, Perplexity AI, Google Gemini) parse JSON-LD schemas to extract authoritative facts. Inject the following scripts into your page \`<head>\`:\n\n`;

    for (const sg of schemaGaps) {
      md += `### Missing \`@type ${sg.schemaType}\` (${sg.status})\n`;
      md += `* **Citation Impact:** ${sg.impactReason}\n`;
      md += `* **Required Attributes:** \`${sg.missingProperties.join(", ")}\`\n\n`;
      md += "```json\n" + sg.recommendedJsonLd + "\n```\n\n";
    }

    md += `## 2. 📊 Factual Benchmark Disparities (Zero-Extrapolation Evidence)\n\n`;
    md += `| Metric / Attribute | Winning Competitor (${competitorPayload.domain}) | Your Brand (${brandPayload.domain}) | Action Required | Source Link |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;
    for (const bg of benchmarkGaps) {
      const brandVal = bg.brandValue || "Omitted / Vague";
      md += `| **${bg.metricName}** | \`${bg.competitorValue}\` | *${brandVal}* | ${bg.recommendation} | [Verify Source ↗](${bg.sourceUrl}) |\n`;
    }
    md += `\n`;

    md += `## 3. 🎯 High-Priority Topic Entities for Semantic Coverage\n\n`;
    for (const eg of entityGaps) {
      md += `* **${eg.entityName}** [\`${eg.citationWeight}\`]: ${eg.actionPlan} *(Search Context: ${eg.searchRelevance})*\n`;
    }
    md += `\n`;

    md += `## 4. 📝 Recommended Copywriting & Section Updates\n\n`;
    md += `### Recommended Hero & Subtitle Copy\n`;
    md += `> **Current:** "${brandPayload.metaDescription || brandPayload.title}"\n`;
    md += `> **Recommended Update:** "${brandPayload.title} — Built for modern teams with sub-second performance, transparent pricing, and SOC-2 enterprise compliance."\n\n`;

    md += `### Recommended Comparison Table Section\n`;
    md += `Add a dedicated comparison matrix against ${competitorPayload.domain} clearly highlighting your advantages across pricing, SLAs, and technical integrations.\n`;

    return {
      title,
      targetQuery: query,
      brandDomain: brandPayload.domain,
      competitorDomain: competitorPayload.domain,
      executiveSummary,
      missingSchemasSummary: schemaGaps.map(s => s.schemaType),
      benchmarkComparisonTable: "",
      topicEntitiesCoverage: entityGaps.map(e => e.entityName),
      suggestedPageSections: ["Hero update", "Comparison Table", "JSON-LD Injection"],
      markdownContent: md
    };
  }

  static generateJiraTicket(
    query: string,
    brandPayload: ScrapedPayload,
    competitorPayload: ScrapedPayload,
    schemaGaps: SchemaGap[],
    benchmarkGaps: BenchmarkGap[],
    entityGaps: EntityGap[]
  ): JiraTicket {
    const ticketKey = "PEEC-408";
    const summary = `[GEO-Remediation] Implement Schema.org JSON-LD and Factual Proof Points for ${brandPayload.domain}`;
    const storyPoints = 5;
    const component = "AI-Gateway";
    const assigneeRole = "Frontend / Growth Engineering Squad";

    const gherkin = `Feature: Diagnostic Side-by-Side Content Remediation
  AS A Growth Marketing Manager tracking prompts on Peec AI,
  I WANT TO inspect the semantic entity delta against winning competitor citations,
  SO THAT I can immediately update my pages with missing data to earn LLM citations.

  Scenario: Render side-by-side gap and copyable JSON-LD schemas
    GIVEN a tracked prompt "${query}" where ${brandPayload.domain} is unmentioned
    WHEN the user triggers citation remediation against ${competitorPayload.domain}
    THEN render missing JSON-LD schema blocks (@type SoftwareApplication, FAQPage)
    AND display verbatim competitor benchmark proof points with primary source links
    AND output 1-click Markdown Content Brief in < 1.5s (cached payload)
    
  Scenario: Graceful Anti-Bot Degradation
    GIVEN a target competitor URL protected by Cloudflare WAF or returning 403
    WHEN the deterministic scraper ingests the page
    THEN fallback gracefully to domain-level signals without raising a 500 error.`;

    const inScope = [
      "Side-by-side entity and factual delta parser",
      "JSON-LD schema (@type SoftwareApplication, FAQPage) injector generation",
      "Instant 1-click Markdown Content Brief export for agencies",
      "Asynchronous processing with 24-hour cache TTL (< 1.5s SLA)",
      "Graceful 403 / anti-bot fallback handler",
      "Auditable raw scraped payload drawer with primary source anchors"
    ];

    const outOfScope = [
      "Direct CMS auto-publishing (WordPress/Webflow API integration)",
      "Automated cold backlink / PR email outreach",
      "Real-time bypass scraping behind paid paywalls",
      "Multi-tenant workspace role permissions (RBAC)",
      "Custom LLM model fine-tuning"
    ];

    const dod = [
      "Unit tests passing across schema parsing and 403 degradation",
      "Cached modal retrieval verified under < 1.5s SLA",
      "Zero-extrapolation rate: 100% of cited facts verified against primary DOM",
      "Security review approved for public DOM extraction"
    ];

    let jiraMd = `# 🎫 Jira Story: ${ticketKey}\n\n`;
    jiraMd += `* **Ticket Key:** \`${ticketKey}\`\n`;
    jiraMd += `* **Summary:** ${summary}\n`;
    jiraMd += `* **Issue Type:** \`Story\`\n`;
    jiraMd += `* **Story Points:** \`${storyPoints} SP\`\n`;
    jiraMd += `* **Component:** \`${component}\`\n`;
    jiraMd += `* **Assignee:** \`${assigneeRole}\`\n\n`;
    jiraMd += `---\n\n### 📖 User Story & Gherkin Acceptance Criteria\n\n`;
    jiraMd += "```gherkin\n" + gherkin + "\n```\n\n";
    jiraMd += `### 🎯 V1 Scope Matrix (Agile Boundaries)\n\n`;
    jiraMd += `| ✅ In-Scope (Version 1 MVP) | 🛑 Explicitly Out-of-Scope (V1 Limits) |\n`;
    jiraMd += `| :--- | :--- |\n`;
    for (let i = 0; i < Math.max(inScope.length, outOfScope.length); i++) {
      const ins = inScope[i] ? `• ${inScope[i]}` : "";
      const out = outOfScope[i] ? `🛑 ${outOfScope[i]}` : "";
      jiraMd += `| ${ins} | ${out} |\n`;
    }
    jiraMd += `\n### 🏁 Definition of Done (DoD)\n\n`;
    for (const d of dod) {
      jiraMd += `* [ ] ${d}\n`;
    }

    return {
      ticketKey,
      summary,
      issueType: "Story",
      storyPoints,
      component,
      assigneeRole,
      gherkinScenarios: gherkin,
      v1InScope: inScope,
      v1ScopeLimits: outOfScope,
      definitionOfDone: dod,
      jiraMarkdown: jiraMd
    };
  }
}
